[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.bloat]
install_crate = "cargo-bloat"
command = "cargo"
args = ["bloat", "--release", "--all-features"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
